import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from '@/components/Providers'
import AppBar from '@/components/AppBar'

interface Props {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body>
        <Providers>
         <AppBar/>
         {props.children}
        </Providers>
      </body>
    </html>
  )
}
